### ISSUE TITLE
CodeMetricsTask for maven:com.zaxxer:HikariCP:2.4.1 fails with ParseException

### ISSUE THREAD

**Issue by fridex** [fabric8-analytics/fabric8-analytics-worker#145] opened 2017-07-20 08:58 UTC
```
{"task_name": "code_metrics", "node_args": {"recursive_limit": 0, "version": "2.4.1", "force": true, "ecosystem": "maven", "force_graph_sync": false, "document_id": 1116663, "_release": "maven:com.zaxxer:HikariCP:2.4.1", "_audit": {"version": "v1", "started_at": "2017-07-18T07:12:54.363986", "ended_at": "2017-07-18T07:12:54.526150"}, "name": "com.zaxxer:HikariCP"}, "flow_name": "bayesianAnalysisFlow", "event": "TASK_START", "task_id": "93ee3a1c-89f2-444a-a85c-31a7b8544cdd", "queue": "prod_ingestion_CodeMetricsTask_v0", "parent": {}, "dispatcher_id": "c3426e26-d433-4916-b16e-8587dca5ec14"}
2017-07-18 08:29:43,913 [WARNING] CodeMetricsTask: Executing command failed, return value: 1, stderr: 'ParseException in /var/lib/f8a_worker/worker_data/maven/com.zaxxer:HikariCP/2.4.1/extracted_jar/com/zaxxer/hikari/pool/HikariPool.java
Last useful checkpoint: "com.zaxxer.hikari.pool.HikariPoolcom.zaxxer.hikari.pool.HikariPool.HikariPool(HikariConfig)"
Encountered " ">" "> "" at line 116, column 46.
Was expecting one of:
    "boolean" ...
    "byte" ...
    "char" ...
    "double" ...
    "float" ...
    "int" ...
    "long" ...
    "short" ...
    <IDENTIFIER> ...
    "?" ...
    "boolean" ...
    "char" ...
    "byte" ...
    "short" ...
    "int" ...
    "long" ...
    "float" ...
    "double" ...
    <IDENTIFIER> ...
    "?" ...
    "?" ...
    "?" ...
    "?" ...
    
ParseException in /var/lib/f8a_worker/worker_data/maven/com.zaxxer:HikariCP/2.4.1/extracted_jar/com/zaxxer/hikari/pool/PoolBagEntry.java
Last useful checkpoint: "com.zaxxer.hikari.pool.PoolBagEntrycom.zaxxer.hikari.pool.PoolBagEntry.PoolBagEntry(Connection,HikariPool)"
Encountered " ">" "> "" at line 79, column 42.
Was expecting one of:
    "boolean" ...
    "byte" ...
    "char" ...
    "double" ...
    "float" ...
    "int" ...
    "long" ...
    "short" ...
    <IDENTIFIER> ...
    "?" ...
    "boolean" ...
    "char" ...
    "byte" ...
    "short" ...
    "int" ...
    "long" ...
    "float" ...
    "double" ...
    <IDENTIFIER> ...
    "?" ...
    "?" ...
    "?" ...
    "?" ...
    
ParseException in /var/lib/f8a_worker/worker_data/maven/com.zaxxer:HikariCP/2.4.1/extracted_jar/com/zaxxer/hikari/pool/PoolElf.java
Last useful checkpoint: "com.zaxxer.hikari.pool.PoolElf.isConnectionAlive(Connection,Throwable)"
Encountered " "(" "( "" at line 219, column 14.
Was expecting:
    "{" ...
    
ParseException in /var/lib/f8a_worker/worker_data/maven/com.zaxxer:HikariCP/2.4.1/extracted_jar/com/zaxxer/hikari/proxy/ConnectionProxy.java
Last useful checkpoint: "com.zaxxer.hikari.proxy.ConnectionProxy"
Encountered " ">" "> "" at line 64, column 32.
Was expecting one of:
    "boolean" ...
    "byte" ...
    "char" ...
    "double" ...
    "float" ...
    "int" ...
    "long" ...
    "short" ...
    <IDENTIFIER> ...
    "?" ...
    "boolean" ...
    "char" ...
    "byte" ...
    "short" ...
    "int" ...
    "long" ...
    "float" ...
    "double" ...
    <IDENTIFIER> ...
    "?" ...
    "?" ...
    "?" ...
    "?" ...
    
ParseException in /var/lib/f8a_worker/worker_data/maven/com.zaxxer:HikariCP/2.4.1/extracted_jar/com/zaxxer/hikari/proxy/JavassistProxyFactory.java
Last useful checkpoint: "com.zaxxer.hikari.proxy.JavassistProxyFactory.generateProxyClass(T,String,String)"
Encountered " ">" "> "" at line 121, column 43.
Was expecting one of:
    "boolean" ...
    "byte" ...
    "char" ...
    "double" ...
    "float" ...
    "int" ...
    "long" ...
    "short" ...
    <IDENTIFIER> ...
    "?" ...
    "boolean" ...
    "char" ...
    "byte" ...
    "short" ...
    "int" ...
    "long" ...
    "float" ...
    "double" ...
    <IDENTIFIER> ...
    "?" ...
    "?" ...
    "?" ...
    "?" ...
    
ParseException in /var/lib/f8a_worker/worker_data/maven/com.zaxxer:HikariCP/2.4.1/extracted_jar/com/zaxxer/hikari/util/ConcurrentBag.java
Last useful checkpoint: "com.zaxxer.hikari.util.ConcurrentBagcom.zaxxer.hikari.util.ConcurrentBag.ConcurrentBag(IBagStateListener)"
Encountered " ">" "> "" at line 94, column 50.
Was expecting one of:
    "boolean" ...
    "byte" ...
    "char" ...
    "double" ...
    "float" ...
    "int" ...
    "long" ...
    "short" ...
    <IDENTIFIER> ...
    "?" ...
    "boolean" ...
    "char" ...
    "byte" ...
    "short" ...
    "int" ...
    "long" ...
    "float" ...
    "double" ...
    <IDENTIFIER> ...
    "?" ...
    "?" ...
    "?" ...
    "?" ...
    
ParseException in /var/lib/f8a_worker/worker_data/maven/com.zaxxer:HikariCP/2.4.1/extracted_jar/com/zaxxer/hikari/util/PropertyElf.java
Last useful checkpoint: "com.zaxxer.hikari.util.PropertyElf.getPropertyNames(Class)"
Encountered " ">" "> "" at line 77, column 41.
Was expecting one of:
    "boolean" ...
    "byte" ...
    "char" ...
    "double" ...
    "float" ...
    "int" ...
    "long" ...
    "short" ...
    <IDENTIFIER> ...
    "?" ...
    "boolean" ...
    "char" ...
    "byte" ...
    "short" ...
    "int" ...
    "long" ...
    "float" ...
    "double" ...
    <IDENTIFIER> ...
    "?" ...
    "?" ...
    "?" ...
    "?" ...
    
ParseException in /var/lib/f8a_worker/worker_data/maven/com.zaxxer:HikariCP/2.4.1/extracted_jar/com/zaxxer/hikari/util/Sequence.java
Last useful checkpoint: "com.zaxxer.hikari.util.Sequence.DropwizardSequence.increment()"
Encountered " "|" "| "" at line 106, column 40.
Was expecting one of:
    "assert" ...
    "enum" ...
    <IDENTIFIER> ...
    "..." ...
    
ParseException in /var/lib/f8a_worker/worker_data/maven/com.zaxxer:HikariCP/2.4.1/extracted_jar/com/zaxxer/hikari/util/UtilityElf.java
Last useful checkpoint: "com.zaxxer.hikari.util.UtilityElf.createThreadPoolExecutor(int,String,ThreadFactory,RejectedExecutionHandler)"
Encountered " ">" "> "" at line 98, column 69.
Was expecting one of:
    "boolean" ...
    "byte" ...
    "char" ...
    "double" ...
    "float" ...
    "int" ...
    "long" ...
    "short" ...
    <IDENTIFIER> ...
    "?" ...
    "boolean" ...
    "char" ...
    "byte" ...
    "short" ...
    "int" ...
    "long" ...
    "float" ...
    "double" ...
    <IDENTIFIER> ...
    "?" ...
    "?" ...
    "?" ...
    "?" ...
    
ParseException in /var/lib/f8a_worker/worker_data/maven/com.zaxxer:HikariCP/2.4.1/extracted_jar/com/zaxxer/hikari/HikariConfig.java
Last useful checkpoint: "com.zaxxer.hikari.HikariConfig.logConfiguration()"
Encountered " ">" "> "" at line 827, column 53.
Was expecting one of:
    "boolean" ...
    "byte" ...
    "char" ...
    "double" ...
    "float" ...
    "int" ...
    "long" ...
    "short" ...
    <IDENTIFIER> ...
    "?" ...
    "boolean" ...
    "char" ...
    "byte" ...
    "short" ...
    "int" ...
    "long" ...
    "float" ...
    "double" ...
    <IDENTIFIER> ...
    "?" ...
    "?" ...
    "?" ...
    "?" ...
    


' 
2017-07-18 08:29:43,914 [WARNING] CodeMetricsTask: JavaNCSS tool reported some errors: ParseException in /var/lib/f8a_worker/worker_data/maven/com.zaxxer:HikariCP/2.4.1/extracted_jar/com/zaxxer/hikari/pool/HikariPool.java
Last useful checkpoint: "com.zaxxer.hikari.pool.HikariPoolcom.zaxxer.hikari.pool.HikariPool.HikariPool(HikariConfig)"
Encountered " ">" "> "" at line 116, column 46.
Was expecting one of:
    "boolean" ...
    "byte" ...
    "char" ...
    "double" ...
    "float" ...
    "int" ...
    "long" ...
    "short" ...
    <IDENTIFIER> ...
    "?" ...
    "boolean" ...
    "char" ...
    "byte" ...
    "short" ...
    "int" ...
    "long" ...
    "float" ...
    "double" ...
    <IDENTIFIER> ...
    "?" ...
    "?" ...
    "?" ...
    "?" ...
    
ParseException in /var/lib/f8a_worker/worker_data/maven/com.zaxxer:HikariCP/2.4.1/extracted_jar/com/zaxxer/hikari/pool/PoolBagEntry.java
Last useful checkpoint: "com.zaxxer.hikari.pool.PoolBagEntrycom.zaxxer.hikari.pool.PoolBagEntry.PoolBagEntry(Connection,HikariPool)"
Encountered " ">" "> "" at line 79, column 42.
Was expecting one of:
    "boolean" ...
    "byte" ...
    "char" ...
    "double" ...
    "float" ...
    "int" ...
    "long" ...
    "short" ...
    <IDENTIFIER> ...
    "?" ...
    "boolean" ...
    "char" ...
    "byte" ...
    "short" ...
    "int" ...
    "long" ...
    "float" ...
    "double" ...
    <IDENTIFIER> ...
    "?" ...
    "?" ...
    "?" ...
    "?" ...
    
ParseException in /var/lib/f8a_worker/worker_data/maven/com.zaxxer:HikariCP/2.4.1/extracted_jar/com/zaxxer/hikari/pool/PoolElf.java
Last useful checkpoint: "com.zaxxer.hikari.pool.PoolElf.isConnectionAlive(Connection,Throwable)"
Encountered " "(" "( "" at line 219, column 14.
Was expecting:
    "{" ...
    
ParseException in /var/lib/f8a_worker/worker_data/maven/com.zaxxer:HikariCP/2.4.1/extracted_jar/com/zaxxer/hikari/proxy/ConnectionProxy.java
Last useful checkpoint: "com.zaxxer.hikari.proxy.ConnectionProxy"
Encountered " ">" "> "" at line 64, column 32.
Was expecting one of:
    "boolean" ...
    "byte" ...
    "char" ...
    "double" ...
    "float" ...
    "int" ...
    "long" ...
    "short" ...
    <IDENTIFIER> ...
    "?" ...
    "boolean" ...
    "char" ...
    "byte" ...
    "short" ...
    "int" ...
    "long" ...
    "float" ...
    "double" ...
    <IDENTIFIER> ...
    "?" ...
    "?" ...
    "?" ...
    "?" ...
    
ParseException in /var/lib/f8a_worker/worker_data/maven/com.zaxxer:HikariCP/2.4.1/extracted_jar/com/zaxxer/hikari/proxy/JavassistProxyFactory.java
Last useful checkpoint: "com.zaxxer.hikari.proxy.JavassistProxyFactory.generateProxyClass(T,String,String)"
Encountered " ">" "> "" at line 121, column 43.
Was expecting one of:
    "boolean" ...
    "byte" ...
    "char" ...
    "double" ...
    "float" ...
    "int" ...
    "long" ...
    "short" ...
    <IDENTIFIER> ...
    "?" ...
    "boolean" ...
    "char" ...
    "byte" ...
    "short" ...
    "int" ...
    "long" ...
    "float" ...
    "double" ...
    <IDENTIFIER> ...
    "?" ...
    "?" ...
    "?" ...
    "?" ...
    
ParseException in /var/lib/f8a_worker/worker_data/maven/com.zaxxer:HikariCP/2.4.1/extracted_jar/com/zaxxer/hikari/util/ConcurrentBag.java
Last useful checkpoint: "com.zaxxer.hikari.util.ConcurrentBagcom.zaxxer.hikari.util.ConcurrentBag.ConcurrentBag(IBagStateListener)"
Encountered " ">" "> "" at line 94, column 50.
Was expecting one of:
    "boolean" ...
    "byte" ...
    "char" ...
    "double" ...
    "float" ...
    "int" ...
    "long" ...
    "short" ...
    <IDENTIFIER> ...
    "?" ...
    "boolean" ...
    "char" ...
    "byte" ...
    "short" ...
    "int" ...
    "long" ...
    "float" ...
    "double" ...
    <IDENTIFIER> ...
    "?" ...
    "?" ...
    "?" ...
    "?" ...
    
ParseException in /var/lib/f8a_worker/worker_data/maven/com.zaxxer:HikariCP/2.4.1/extracted_jar/com/zaxxer/hikari/util/PropertyElf.java
Last useful checkpoint: "com.zaxxer.hikari.util.PropertyElf.getPropertyNames(Class)"
Encountered " ">" "> "" at line 77, column 41.
Was expecting one of:
    "boolean" ...
    "byte" ...
    "char" ...
    "double" ...
    "float" ...
    "int" ...
    "long" ...
    "short" ...
    <IDENTIFIER> ...
    "?" ...
    "boolean" ...
    "char" ...
    "byte" ...
    "short" ...
    "int" ...
    "long" ...
    "float" ...
    "double" ...
    <IDENTIFIER> ...
    "?" ...
    "?" ...
    "?" ...
    "?" ...
    
ParseException in /var/lib/f8a_worker/worker_data/maven/com.zaxxer:HikariCP/2.4.1/extracted_jar/com/zaxxer/hikari/util/Sequence.java
Last useful checkpoint: "com.zaxxer.hikari.util.Sequence.DropwizardSequence.increment()"
Encountered " "|" "| "" at line 106, column 40.
Was expecting one of:
    "assert" ...
    "enum" ...
    <IDENTIFIER> ...
    "..." ...
    
ParseException in /var/lib/f8a_worker/worker_data/maven/com.zaxxer:HikariCP/2.4.1/extracted_jar/com/zaxxer/hikari/util/UtilityElf.java
Last useful checkpoint: "com.zaxxer.hikari.util.UtilityElf.createThreadPoolExecutor(int,String,ThreadFactory,RejectedExecutionHandler)"
Encountered " ">" "> "" at line 98, column 69.
Was expecting one of:
    "boolean" ...
    "byte" ...
    "char" ...
    "double" ...
    "float" ...
    "int" ...
    "long" ...
    "short" ...
    <IDENTIFIER> ...
    "?" ...
    "boolean" ...
    "char" ...
    "byte" ...
    "short" ...
    "int" ...
    "long" ...
    "float" ...
    "double" ...
    <IDENTIFIER> ...
    "?" ...
    "?" ...
    "?" ...
    "?" ...
    
ParseException in /var/lib/f8a_worker/worker_data/maven/com.zaxxer:HikariCP/2.4.1/extracted_jar/com/zaxxer/hikari/HikariConfig.java
Last useful checkpoint: "com.zaxxer.hikari.HikariConfig.logConfiguration()"
Encountered " ">" "> "" at line 827, column 53.
Was expecting one of:
    "boolean" ...
    "byte" ...
    "char" ...
    "double" ...
    "float" ...
    "int" ...
    "long" ...
    "short" ...
    <IDENTIFIER> ...
    "?" ...
    "boolean" ...
    "char" ...
    "byte" ...
    "short" ...
    "int" ...
    "long" ...
    "float" ...
    "double" ...
    <IDENTIFIER> ...
    "?" ...
    "?" ...
    "?" ...
    "?" ...

```

**Comment by jpopelka** [comment] 2017-07-24 08:09
Looks like duplicate of #143

**Comment by msrb** [comment] 2017-08-07 09:53
Yep, Jirka is right. The tool that we use for Java simply doesn't support Java 7/8 syntax.

**Closed by msrb** 2017-08-07 09:53 UTC
