### ISSUE TITLE
libraries.io - list index out of range error on release tag

### ISSUE THREAD

**Issue by fridex** [fabric8-analytics/fabric8-analytics-worker#436] opened 2017-11-09 12:20 UTC
From production:

```json
{"task_id": "9f571db8-e5b4-4f3d-8491-13fb4672dd6a", "what": "Traceback (most recent call last):\n File \"/usr/lib/python3.4/site-packages/selinon/selinonTaskEnvelope.py\", line 115, in run\n result = task.run(node_args)\n File \"/usr/lib/python3.4/site-packages/f8a_worker/base.py\", line 41, in run\n result = self.execute(node_args)\n File \"/usr/lib/python3.4/site-packages/f8a_worker/workers/libraries_io.py\", line 97, in execute\n details = {'releases': self.get_releases(page),\n File \"/usr/lib/python3.4/site-packages/f8a_worker/workers/libraries_io.py\", line 41, in get_releases\n releases_tag = page.find_all('div', class_=\"col-md-4 sidebar\")[-1]\nIndexError: list index out of range\n", "task_name": "libraries_io", "retried_count": 0, "dispatcher_id": "fff99184-ffce-46f5-9684-d472d348ab5c", "event": "TASK_FAILURE", "parent": {}, "node_args": {"_audit": {"started_at": "2017-11-04T19:50:47.773263", "ended_at": "2017-11-04T19:50:47.965266", "version": "v1"}, "recursive_limit": 0, "name": "marshal", "ecosystem": "npm", "url": "git://github.com/clayzermk1/node-marshal.git", "document_id": 1420606, "_release": "npm:marshal:None"}, "flow_name": "bayesianPackageAnalysisFlow", "queue": "prod_ingestion_libraries_io_v0"}
```

Traceback:
```python
 Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/selinon/selinonTaskEnvelope.py", line 115, in run
    result = task.run(node_args)
  File "/usr/lib/python3.4/site-packages/f8a_worker/base.py", line 41, in run
    result = self.execute(node_args)
  File "/usr/lib/python3.4/site-packages/f8a_worker/workers/libraries_io.py", line 97, in execute
    details = {'releases': self.get_releases(page),
  File "/usr/lib/python3.4/site-packages/f8a_worker/workers/libraries_io.py", line 41, in get_releases
    releases_tag = page.find_all('div', class_="col-md-4 sidebar")[-1]
IndexError: list index out of range
```

**Comment by jpopelka** [comment] 2017-11-23 12:52
duplicate of #327

**Closed by jpopelka** 2017-11-23 12:52 UTC
